#!/usr/bin/env bun
/**
 * Interactive CLI script to set up .env file from .env.example
 * Run with: bun setup-env.ts  (or: bun run setup)
 */

import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import * as readline from "readline";

// ANSI color codes for terminal output
const c = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  cyan: "\x1b[36m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  red: "\x1b[31m",
  magenta: "\x1b[35m",
  blue: "\x1b[34m",
};

const TEMPLATE_PATH = join(import.meta.dir, ".env.example");
const ENV_PATH = join(import.meta.dir, ".env");

interface EnvEntry {
  key: string;
  comment: string[];
  existingValue?: string;
}

function parseTemplate(content: string): EnvEntry[] {
  const lines = content.split("\n");
  const entries: EnvEntry[] = [];
  let currentComments: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed.startsWith("#")) {
      currentComments.push(trimmed.slice(1).trim());
    } else if (trimmed.includes("=")) {
      const [key, ...valueParts] = trimmed.split("=");
      const existingValue = valueParts.join("=").trim();

      entries.push({
        key: key.trim(),
        comment: currentComments,
        existingValue: existingValue || undefined,
      });
      currentComments = [];
    } else if (trimmed === "") {
      currentComments = [];
    }
  }

  return entries;
}

function loadExistingEnv(): Map<string, string> {
  const values = new Map<string, string>();

  if (existsSync(ENV_PATH)) {
    const content = readFileSync(ENV_PATH, "utf-8");
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith("#") && trimmed.includes("=")) {
        const [key, ...valueParts] = trimmed.split("=");
        values.set(key.trim(), valueParts.join("=").trim());
      }
    }
  }

  return values;
}

function prompt(question: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer);
    });
  });
}

async function main() {
  console.log(
    `\n${c.bold}${c.cyan}🚀 Astro Agents Playground${c.reset} ${c.dim}— Environment Setup${c.reset}\n`
  );

  if (!existsSync(TEMPLATE_PATH)) {
    console.error(`${c.red}❌ Error: .env.example not found${c.reset}`);
    process.exit(1);
  }

  const templateContent = readFileSync(TEMPLATE_PATH, "utf-8");
  const entries = parseTemplate(templateContent);

  if (entries.length === 0) {
    console.log(`${c.green}✅ No environment variables to configure.${c.reset}`);
    process.exit(0);
  }

  const existingValues = loadExistingEnv();
  const newValues = new Map<string, string>();

  console.log(
    `${c.dim}Found ${c.reset}${c.bold}${entries.length}${c.reset}${c.dim} variable${entries.length > 1 ? "s" : ""} to configure:${c.reset}\n`
  );

  for (const entry of entries) {
    const existing = existingValues.get(entry.key);

    // Show description if available
    if (entry.comment.length > 0) {
      console.log(`  ${c.dim}${entry.comment.join(`\n  `)}${c.reset}`);
    }

    let promptText = `  ${c.cyan}${entry.key}${c.reset}`;
    if (existing) {
      const masked =
        existing.length > 8
          ? existing.slice(0, 4) + "..." + existing.slice(-4)
          : "****";
      promptText += ` ${c.dim}[current: ${c.yellow}${masked}${c.dim}]${c.reset}`;
    }
    promptText += `${c.dim}:${c.reset} `;

    const value = await prompt(promptText);

    if (value.trim()) {
      newValues.set(entry.key, value.trim());
      console.log(`  ${c.green}✓${c.reset} ${c.dim}Value set${c.reset}\n`);
    } else if (existing) {
      newValues.set(entry.key, existing);
      console.log(`  ${c.blue}→${c.reset} ${c.dim}Keeping existing value${c.reset}\n`);
    } else if (entry.existingValue) {
      newValues.set(entry.key, entry.existingValue);
      console.log(`  ${c.blue}→${c.reset} ${c.dim}Using default value${c.reset}\n`);
    } else {
      console.log(`  ${c.yellow}⚠${c.reset}  ${c.yellow}Warning:${c.reset} ${c.dim}${entry.key} left empty${c.reset}\n`);
    }
  }

  // Build the .env file content
  let envContent = "# Generated by setup-env.ts\n";
  envContent += `# Last updated: ${new Date().toISOString()}\n\n`;

  for (const entry of entries) {
    if (entry.comment.length > 0) {
      envContent += entry.comment.map((comment) => `# ${comment}`).join("\n") + "\n";
    }
    envContent += `${entry.key}=${newValues.get(entry.key) || ""}\n\n`;
  }

  writeFileSync(ENV_PATH, envContent.trim() + "\n");

  console.log(`\n${c.green}${c.bold}✅ .env file created successfully!${c.reset}`);
  console.log(`   ${c.dim}Location:${c.reset} ${c.cyan}${ENV_PATH}${c.reset}\n`);
}

main().catch((error) => {
  console.error(`${c.red}${c.bold}Error:${c.reset}`, error);
  process.exit(1);
});

