package account

// deniedNames contains well-known brand and company names that cannot be used as account names.
// This protects against impersonation and squatting of popular identities.
var deniedNames = map[string]bool{
	// Big Tech
	"google":     true,
	"alphabet":   true,
	"microsoft":  true,
	"apple":      true,
	"amazon":     true,
	"aws":        true,
	"meta":       true,
	"facebook":   true,
	"instagram":  true,
	"whatsapp":   true,
	"netflix":    true,
	"twitter":    true,
	"x":          true,
	"tiktok":     true,
	"bytedance":  true,
	"youtube":    true,
	"linkedin":   true,
	"snapchat":   true,
	"pinterest":  true,
	"reddit":     true,
	"discord":    true,
	"telegram":   true,
	"signal":     true,
	"wechat":     true,
	"slack":      true,
	"zoom":       true,
	"skype":      true,
	"spotify":    true,
	"github":     true,
	"gitlab":     true,
	"bitbucket":  true,
	"atlassian":  true,
	"jira":       true,
	"confluence": true,
	"trello":     true,
	"notion":     true,
	"figma":      true,
	"canva":      true,
	"dropbox":    true,
	"box":        true,
	"adobe":      true,
	"autodesk":   true,
	"salesforce": true,
	"hubspot":    true,
	"zendesk":    true,
	"intercom":   true,
	"oracle":     true,
	"sap":        true,
	"ibm":        true,
	"intel":      true,
	"amd":        true,
	"nvidia":     true,
	"qualcomm":   true,
	"cisco":      true,
	"vmware":     true,
	"broadcom":   true,
	"dell":       true,
	"hp":         true,
	"lenovo":     true,
	"samsung":    true,
	"sony":       true,
	"lg":         true,
	"huawei":     true,
	"xiaomi":     true,
	"oppo":       true,
	"vivo":       true,
	"oneplus":    true,
	"motorola":   true,
	"nokia":      true,
	"ericsson":   true,

	// Cloud & Infrastructure
	"azure":        true,
	"gcp":          true,
	"cloudflare":   true,
	"digitalocean": true,
	"heroku":       true,
	"vercel":       true,
	"netlify":      true,
	"fastly":       true,
	"akamai":       true,
	"cloudfront":   true,
	"linode":       true,
	"vultr":        true,
	"hetzner":      true,
	"ovh":          true,

	// Developer Tools & OSS
	"hashicorp":     true,
	"terraform":     true,
	"kubernetes":    true,
	"docker":        true,
	"ansible":       true,
	"puppet":        true,
	"chef":          true,
	"jenkins":       true,
	"circleci":      true,
	"travis":        true,
	"datadog":       true,
	"splunk":        true,
	"elastic":       true,
	"elasticsearch": true,
	"kibana":        true,
	"grafana":       true,
	"prometheus":    true,
	"mongodb":       true,
	"postgresql":    true,
	"mysql":         true,
	"redis":         true,
	"kafka":         true,
	"rabbitmq":      true,
	"nginx":         true,
	"apache":        true,
	"linux":         true,
	"ubuntu":        true,
	"debian":        true,
	"fedora":        true,
	"redhat":        true,
	"centos":        true,
	"suse":          true,
	"archlinux":     true,
	"postman":       true,
	"insomnia":      true,
	"twilio":        true,
	"sendgrid":      true,
	"segment":       true,
	"stripe":        true,
	"braintree":     true,
	"plaid":         true,
	"okta":          true,
	"auth0":         true,
	"pagerduty":     true,
	"opsgenie":      true,
	"sentry":        true,
	"rollbar":       true,
	"newrelic":      true,
	"dynatrace":     true,

	// AI / ML Companies
	"openai":      true,
	"anthropic":   true,
	"deepmind":    true,
	"cohere":      true,
	"mistral":     true,
	"stability":   true,
	"midjourney":  true,
	"huggingface": true,
	"replicate":   true,
	"together":    true,
	"perplexity":  true,
	"jasper":      true,
	"runway":      true,
	"cursor":      true,

	// Finance & Payments
	"paypal":        true,
	"venmo":         true,
	"visa":          true,
	"mastercard":    true,
	"amex":          true,
	"discover":      true,
	"chase":         true,
	"wellsfargo":    true,
	"bankofamerica": true,
	"citibank":      true,
	"citi":          true,
	"goldman":       true,
	"jpmorgan":      true,
	"morganstanley": true,
	"blackrock":     true,
	"vanguard":      true,
	"fidelity":      true,
	"schwab":        true,
	"robinhood":     true,
	"coinbase":      true,
	"binance":       true,
	"kraken":        true,
	"opensea":       true,
	"square":        true,
	"cash":          true,
	"cashapp":       true,
	"revolut":       true,
	"wise":          true,
	"sofi":          true,

	// Retail & E-commerce
	"walmart":     true,
	"target":      true,
	"costco":      true,
	"ebay":        true,
	"etsy":        true,
	"wayfair":     true,
	"shopify":     true,
	"woocommerce": true,
	"magento":     true,
	"ikea":        true,

	// Fashion & Consumer Brands
	"nike":         true,
	"adidas":       true,
	"puma":         true,
	"newbalance":   true,
	"reebok":       true,
	"underarmour":  true,
	"lululemon":    true,
	"gap":          true,
	"zara":         true,
	"hm":           true,
	"uniqlo":       true,
	"gucci":        true,
	"prada":        true,
	"lvmh":         true,
	"hermes":       true,
	"chanel":       true,
	"louisvuitton": true,
	"burberry":     true,
	"versace":      true,
	"armani":       true,
	"rolex":        true,
	"rayban":       true,

	// Automotive
	"tesla":       true,
	"ford":        true,
	"gm":          true,
	"toyota":      true,
	"honda":       true,
	"bmw":         true,
	"mercedes":    true,
	"volkswagen":  true,
	"audi":        true,
	"porsche":     true,
	"ferrari":     true,
	"lamborghini": true,
	"rivian":      true,
	"lucid":       true,
	"hyundai":     true,
	"kia":         true,
	"subaru":      true,
	"mazda":       true,
	"nissan":      true,
	"volvo":       true,
	"stellantis":  true,
	"jeep":        true,
	"dodge":       true,
	"chrysler":    true,

	// Media & Entertainment
	"disney":     true,
	"hulu":       true,
	"hbo":        true,
	"max":        true,
	"paramount":  true,
	"peacock":    true,
	"appletv":    true,
	"primevideo": true,
	"cnn":        true,
	"bbc":        true,
	"nbc":        true,
	"abc":        true,
	"cbs":        true,
	"fox":        true,
	"nytimes":    true,
	"wsj":        true,
	"guardian":   true,
	"bloomberg":  true,
	"reuters":    true,
	"forbes":     true,
	"techcrunch": true,
	"theverge":   true,
	"wired":      true,
	"engadget":   true,

	// Telecom
	"att":      true,
	"verizon":  true,
	"tmobile":  true,
	"sprint":   true,
	"comcast":  true,
	"xfinity":  true,
	"charter":  true,
	"cox":      true,
	"vodafone": true,
	"deutsche": true,
	"orange":   true,

	// Travel & Hospitality
	"expedia":        true,
	"booking":        true,
	"airbnb":         true,
	"marriott":       true,
	"hilton":         true,
	"hyatt":          true,
	"ihg":            true,
	"delta":          true,
	"united":         true,
	"american":       true,
	"southwest":      true,
	"jetblue":        true,
	"ryanair":        true,
	"easyjet":        true,
	"lufthansa":      true,
	"emirates":       true,
	"qantas":         true,
	"airfrance":      true,
	"britishairways": true,
	"uber":           true,
	"lyft":           true,

	// Food & Beverage
	"mcdonalds":  true,
	"starbucks":  true,
	"subway":     true,
	"chipotle":   true,
	"dominos":    true,
	"pizzahut":   true,
	"kfc":        true,
	"burgerking": true,
	"wendys":     true,
	"dunkin":     true,
	"cocacola":   true,
	"pepsi":      true,
	"nestle":     true,
	"unilever":   true,
	"kraft":      true,
	"heinz":      true,
	"doordash":   true,
	"ubereats":   true,
	"grubhub":    true,
	"instacart":  true,

	// Healthcare & Pharma
	"pfizer":       true,
	"johnson":      true,
	"merck":        true,
	"abbvie":       true,
	"unitedhealth": true,
	"cvs":          true,
	"walgreens":    true,
	"roche":        true,
	"novartis":     true,
	"astrazeneca":  true,
	"biontech":     true,
	"moderna":      true,
	"sanofi":       true,

	// Government & Institutions
	"gov":        true,
	"government": true,
	"whitehouse": true,
	"congress":   true,
	"senate":     true,
	"pentagon":   true,
	"nasa":       true,
	"fbi":        true,
	"cia":        true,
	"nsa":        true,
	"dhs":        true,
	"fcc":        true,
	"ftc":        true,
	"sec":        true,
	"irs":        true,
	"doj":        true,
	"eu":         true,
	"un":         true,
	"nato":       true,
	"who":        true,
	"imf":        true,
	"worldbank":  true,

	// Misc / Other Notable
	"spacex":      true,
	"starlink":    true,
	"neuralink":   true,
	"palantir":    true,
	"snowflake":   true,
	"databricks":  true,
	"confluent":   true,
	"supabase":    true,
	"neon":        true,
	"planetscale": true,
	"cockroachdb": true,
	"clickhouse":  true,
	"pinecone":    true,
	"weaviate":    true,
	"qdrant":      true,
	"langchain":   true,
	"llamaindex":  true,
	"weights":     true,
	"wandb":       true,
	"scale":       true,
	"labelbox":    true,
	"grammarly":   true,
	"duolingo":    true,
	"coursera":    true,
	"udemy":       true,
	"khan":        true,
	"khanacademy": true,
	"ycombinator": true,
	"sequoia":     true,
	"a16z":        true,
	"andreessen":  true,
	"kleiner":     true,
	"accel":       true,
	"benchmark":   true,
	"lightspeed":  true,
	"general":     true,
	"tiger":       true,
	"softbank":    true,

	// Canadian Tech
	"hootsuite":  true,
	"freshbooks": true,
	"wattpad":    true,
	"opentext":   true,
	"blackberry": true,
	"rim":        true,
	"cgi":        true,
	"kinaxis":    true,
	"descartes":  true,
	"nuvei":      true,
	"d2l":        true,
	"klue":       true,
	"vendasta":   true,
	"absorb":     true,

	// Canadian Telecom
	"bell":      true,
	"rogers":    true,
	"telus":     true,
	"shaw":      true,
	"videotron": true,
	"fido":      true,
	"koodo":     true,
	"chatr":     true,

	// Canadian Banks & Finance
	"rbc":          true,
	"td":           true,
	"bmo":          true,
	"scotiabank":   true,
	"cibc":         true,
	"desjardins":   true,
	"atb":          true,
	"wealthsimple": true,
	"manulife":     true,
	"sunlife":      true,
	"intact":       true,
	"cooperators":  true,

	// Canadian Retail
	"canadiantire": true,
	"loblaws":      true,
	"sobeys":       true,
	"metro":        true,
	"dollarama":    true,
	"hbc":          true,
	"hudsonbay":    true,
	"sportchek":    true,
	"roots":        true,
	"indigo":       true,
	"chapters":     true,
	"simons":       true,

	// Canadian Energy
	"suncor":   true,
	"enbridge": true,
	"cenovus":  true,
	"tcenergy": true,
	"pembina":  true,
	"nutrien":  true,
	"cameco":   true,

	// Canadian Media
	"cbc":          true,
	"ctv":          true,
	"globeandmail": true,
	"torontostar":  true,
	"postmedia":    true,
	"quebecor":     true,

	// Canadian Food & Beverage
	"timhortons": true,
	"saputo":     true,
	"mapleleaf":  true,
	"mccain":     true,

	// Canadian Aerospace & Defense
	"bombardier": true,
	"cae":        true,
	"magellan":   true,

	// Canadian Mining & Resources
	"barrick": true,
	"agnico":  true,
	"kinross": true,
	"teck":    true,

	// Canadian Real Estate & Other
	"brookfield": true,
	"minto":      true,
	"magna":      true,

	// Indian Tech
	"tcs":         true,
	"infosys":     true,
	"wipro":       true,
	"hcltech":     true,
	"techm":       true,
	"mphasis":     true,
	"ltimindtree": true,
	"persistent":  true,
	"hexaware":    true,
	"cyient":      true,
	"zensar":      true,
	"mastek":      true,
	"kpit":        true,
	"tataelxsi":   true,
	"freshworks":  true,
	"zoho":        true,
	"razorpay":    true,
	"zerodha":     true,
	"groww":       true,
	"phonepe":     true,
	"paytm":       true,
	"cred":        true,
	"meesho":      true,
	"zomato":      true,
	"swiggy":      true,
	"ola":         true,
	"olamoney":    true,
	"nykaa":       true,
	"flipkart":    true,
	"snapdeal":    true,
	"bigbasket":   true,
	"blinkit":     true,
	"dunzo":       true,
	"byju":        true,
	"byjus":       true,
	"unacademy":   true,
	"vedantu":     true,
	"cleartax":    true,
	"zepto":       true,
	"ixigo":       true,
	"makemytrip":  true,
	"goibibo":     true,
	"cleartrip":   true,
	"dream11":     true,
	"mpl":         true,
	"games24x7":   true,
	"postpe":      true,
	"slice":       true,
	"jupiter":     true,
	"niyo":        true,
	"fi":          true,
	"setu":        true,
	"open":        true,
	"instamojo":   true,
	"cashfree":    true,

	// Indian Conglomerates & Legacy
	"tata":            true,
	"tatamotors":      true,
	"tatapower":       true,
	"tatasteel":       true,
	"tataconsultancy": true,
	"reliance":        true,
	"jio":             true,
	"jiosaavn":        true,
	"mahindra":        true,
	"birla":           true,
	"adani":           true,
	"bajaj":           true,
	"godrej":          true,
	"hindunilvr":      true,
	"itc":             true,
	"dabur":           true,
	"marico":          true,
	"emami":           true,
	"patanjali":       true,
	"amul":            true,
	"haldirams":       true,
	"mtr":             true,

	// Indian Banks & Finance
	"sbi":          true,
	"hdfc":         true,
	"hdfcbank":     true,
	"icici":        true,
	"icicibank":    true,
	"axisbank":     true,
	"kotak":        true,
	"kotakbank":    true,
	"yes":          true,
	"yesbank":      true,
	"idfc":         true,
	"bandhan":      true,
	"lic":          true,
	"npci":         true,
	"upi":          true,
	"nsdl":         true,
	"sebi":         true,
	"rbi":          true,
	"angelone":     true,
	"upstox":       true,
	"5paisa":       true,
	"policybazaar": true,
	"acko":         true,
	"digit":        true,

	// Indian Telecom
	"airtel":       true,
	"bsnl":         true,
	"mtnl":         true,
	"vodafoneidea": true,
	"vi":           true,

	// Indian E-commerce & Retail
	"myntra":     true,
	"ajio":       true,
	"tatacliq":   true,
	"jiomart":    true,
	"indiamart":  true,
	"tradeindia": true,

	// Indian Media & Entertainment
	"hotstar":        true,
	"jiocinema":      true,
	"sonyliv":        true,
	"zee5":           true,
	"mxplayer":       true,
	"gaana":          true,
	"wynk":           true,
	"hungama":        true,
	"sharechat":      true,
	"moj":            true,
	"josh":           true,
	"inshorts":       true,
	"dailyhunt":      true,
	"ndtv":           true,
	"timesofind":     true,
	"hindustantimes": true,
	"thehindu":       true,
	"economictimes":  true,
	"moneycontrol":   true,

	// Indian Pharma
	"sunpharma": true,
	"drreddy":   true,
	"cipla":     true,
	"lupin":     true,
	"aurobindo": true,
	"divi":      true,
	"biocon":    true,
	"torrent":   true,

	// Indian Aviation & Travel
	"airindia": true,
	"spicejet": true,
	"vistara":  true,
	"goair":    true,
	"oyo":      true,
	"stayfit":  true,

	// UK Tech & Startups
	"arm":          true,
	"monzo":        true,
	"starling":     true,
	"deliveroo":    true,
	"darktrace":    true,
	"ocado":        true,
	"autotrader":   true,
	"rightmove":    true,
	"zoopla":       true,
	"asos":         true,
	"transferwise": true,

	// UK Finance
	"barclays":          true,
	"hsbc":              true,
	"lloyds":            true,
	"natwest":           true,
	"standardchartered": true,
	"legalgeneral":      true,
	"hargreaves":        true,
	"prudential":        true,

	// UK Energy & Industry
	"bp":           true,
	"shell":        true,
	"nationalgrid": true,
	"baesystems":   true,
	"rollsroyce":   true,

	// UK Retail & Consumer
	"tesco":           true,
	"sainsburys":      true,
	"asda":            true,
	"marksandspencer": true,
	"boots":           true,
	"johnlewis":       true,
	"next":            true,
	"primark":         true,

	// UK Telecom & Media
	"bt":          true,
	"sky":         true,
	"itv":         true,
	"virginmedia": true,
	"o2":          true,

	// UK Pharma
	"gsk":             true,
	"glaxosmithkline": true,

	// UK Automotive
	"jaguarlandrover": true,
	"jaguar":          true,
	"landrover":       true,
	"bentley":         true,
	"mclaren":         true,
	"lotus":           true,
	"minicooper":      true,

	// Germany Tech & Industry
	"siemens":    true,
	"bosch":      true,
	"infineon":   true,
	"softwareag": true,

	// Germany Finance
	"deutschebank": true,
	"commerzbank":  true,
	"allianz":      true,
	"munichre":     true,

	// Germany Retail & Consumer
	"lidl":    true,
	"aldi":    true,
	"zalando": true,
	"otto":    true,
	"dm":      true,

	// Germany Chemicals & Energy
	"basf":   true,
	"bayer":  true,
	"henkel": true,
	"eon":    true,
	"rwe":    true,

	// Germany Logistics
	"dhl":          true,
	"deutschepost": true,

	// Germany Media
	"bertelsmann":  true,
	"axelspringer": true,

	// France Tech & Industry
	"capgemini": true,
	"atos":      true,
	"thales":    true,
	"dassault":  true,
	"airbus":    true,

	// France Automotive
	"renault":  true,
	"peugeot":  true,
	"citroen":  true,
	"michelin": true,

	// France Luxury & Retail
	"loreal":    true,
	"kering":    true,
	"cartier":   true,
	"dior":      true,
	"givenchy":  true,
	"ysl":       true,
	"carrefour": true,
	"decathlon": true,

	// France Energy
	"totalenergies": true,
	"total":         true,
	"edf":           true,
	"engie":         true,

	// France Finance & Food
	"bnpparibas":      true,
	"societegenerale": true,
	"creditagricole":  true,
	"axa":             true,
	"danone":          true,
	"pernod":          true,

	// France Media
	"vivendi": true,
	"canal":   true,

	// Italy Automotive & Fashion
	"fiat":         true,
	"alfaromeo":    true,
	"maserati":     true,
	"ducati":       true,
	"piaggio":      true,
	"vespa":        true,
	"dolcegabbana": true,
	"valentino":    true,
	"fendi":        true,
	"bulgari":      true,
	"tods":         true,

	// Italy Food & Finance
	"barilla":   true,
	"ferrero":   true,
	"nutella":   true,
	"campari":   true,
	"lavazza":   true,
	"unicredit": true,
	"eni":       true,
	"enel":      true,

	// Spain
	"telefonica": true,
	"inditex":    true,
	"mango":      true,
	"santander":  true,
	"bbva":       true,
	"caixabank":  true,
	"repsol":     true,
	"iberdrola":  true,
	"seat":       true,
	"amadeus":    true,

	// Netherlands
	"asml":     true,
	"philips":  true,
	"tomtom":   true,
	"ing":      true,
	"abnamro":  true,
	"rabobank": true,
	"aegon":    true,
	"heineken": true,

	// Sweden
	"klarna":        true,
	"king":          true,
	"mojang":        true,
	"polestar":      true,
	"scania":        true,
	"nordea":        true,
	"handelsbanken": true,
	"tele2":         true,

	// Switzerland
	"ubs":          true,
	"creditsuisse": true,
	"juliusbaer":   true,
	"lonza":        true,
	"lindt":        true,
	"nespresso":    true,
	"swatch":       true,
	"omega":        true,
	"tagheuer":     true,
	"abb":          true,
	"glencore":     true,

	// Denmark
	"maersk":      true,
	"vestas":      true,
	"novonordisk": true,
	"lego":        true,
	"danskebank":  true,

	// Finland
	"kone":     true,
	"neste":    true,
	"wartsila": true,

	// Norway
	"equinor": true,
	"telenor": true,
	"dnb":     true,

	// Belgium
	"abinbev": true,
	"stella":  true,
	"kbc":     true,

	// Austria
	"redbull":    true,
	"erstegroup": true,
	"raiffeisen": true,

	// Poland
	"allegro":   true,
	"cdprojekt": true,
	"pkobp":     true,
	"orlen":     true,

	// Czech Republic
	"skoda": true,
	"avast": true,

	// Japan
	"nintendo":     true,
	"panasonic":    true,
	"toshiba":      true,
	"hitachi":      true,
	"fujitsu":      true,
	"ntt":          true,
	"rakuten":      true,
	"line":         true,
	"nec":          true,
	"sharp":        true,
	"canon":        true,
	"nikon":        true,
	"olympus":      true,
	"yamaha":       true,
	"kawasaki":     true,
	"mitsubishi":   true,
	"suzuki":       true,
	"bridgestone":  true,
	"shiseido":     true,
	"muji":         true,
	"softbankcorp": true,
	"docomo":       true,
	"au":           true,
	"kddi":         true,
	"tokio":        true,
	"nomura":       true,
	"mizuho":       true,
	"mufg":         true,
	"smbc":         true,
	"seveneleven":  true,
	"lawson":       true,
	"familymart":   true,

	// South Korea
	"kakao":     true,
	"kakaotalk": true,
	"kakaobank": true,
	"naver":     true,
	"coupang":   true,
	"krafton":   true,
	"nexon":     true,
	"ncsoft":    true,
	"netmarble": true,
	"skgroup":   true,
	"skhynix":   true,
	"lotte":     true,
	"posco":     true,
	"hanwha":    true,
	"hanjin":    true,

	// China
	"alibaba":  true,
	"alipay":   true,
	"taobao":   true,
	"tmall":    true,
	"alicloud": true,
	"tencent":  true,
	"qq":       true,
	"baidu":    true,
	"jd":       true,
	"jdcom":    true,
	"meituan":  true,
	"didi":     true,
	"weibo":    true,
	"bilibili": true,
	"netease":  true,
	"mihoyo":   true,
	"byd":      true,
	"catl":     true,
	"dji":      true,
	"icbc":     true,
	"pingan":   true,
	"ctrip":    true,
	"trip":     true,
	"kuaishou": true,
	"douyin":   true,
	"iqiyi":    true,
	"youku":    true,
	"ant":      true,
	"antgroup": true,
	"unionpay": true,

	// Taiwan
	"tsmc":     true,
	"asus":     true,
	"acer":     true,
	"htc":      true,
	"foxconn":  true,
	"mediatek": true,

	// Southeast Asia
	"grab":      true,
	"seagroup":  true,
	"shopee":    true,
	"lazada":    true,
	"gojek":     true,
	"tokopedia": true,
	"goto":      true,
	"bukalapak": true,
	"traveloka": true,
	"singtel":   true,
	"starhub":   true,
	"dbs":       true,
	"ocbc":      true,
	"uob":       true,

	// Australia & NZ
	"afterpay":     true,
	"zip":          true,
	"telstra":      true,
	"optus":        true,
	"woolworths":   true,
	"coles":        true,
	"wesfarmers":   true,
	"jbhifi":       true,
	"harveynorman": true,
	"bhp":          true,
	"riotinto":     true,
	"fortescue":    true,
	"woodside":     true,
	"anz":          true,
	"commbank":     true,
	"westpac":      true,
	"nab":          true,
	"macquarie":    true,
	"xero":         true,

	// Middle East
	"saudiaramco":  true,
	"aramco":       true,
	"sabic":        true,
	"stc":          true,
	"etisalat":     true,
	"eand":         true,
	"du":           true,
	"careem":       true,
	"noon":         true,
	"talabat":      true,
	"etihad":       true,
	"qatarairways": true,
	"emaar":        true,
	"souq":         true,

	// Africa
	"mtn":         true,
	"safaricom":   true,
	"mpesa":       true,
	"flutterwave": true,
	"paystack":    true,
	"interswitch": true,
	"jumia":       true,
	"naspers":     true,
	"multichoice": true,
	"telkom":      true,

	// Latin America
	"mercadolibre": true,
	"mercadopago":  true,
	"nubank":       true,
	"ifood":        true,
	"rappi":        true,
	"embraer":      true,
	"petrobras":    true,
	"vale":         true,
	"itau":         true,
	"bradesco":     true,
	"americamovil": true,
	"claro":        true,
	"telcel":       true,
	"cemex":        true,
	"femsa":        true,
	"oxxo":         true,
	"latam":        true,
	"copa":         true,
	"xp":           true,
	"btgpactual":   true,
	"totvs":        true,
	"enjoei":       true,

	// US Gaming
	"ea":             true,
	"electronicarts": true,
	"activision":     true,
	"blizzard":       true,
	"epicgames":      true,
	"valve":          true,
	"steam":          true,
	"roblox":         true,
	"unity":          true,
	"take2":          true,
	"rockstar":       true,
	"2k":             true,
	"ubisoft":        true,
	"riot":           true,
	"riotgames":      true,
	"bungie":         true,
	"bethesda":       true,
	"id":             true,

	// US Consulting & Professional Services
	"mckinsey":  true,
	"deloitte":  true,
	"pwc":       true,
	"ey":        true,
	"kpmg":      true,
	"accenture": true,
	"bcg":       true,
	"bain":      true,
	"boozallen": true,
	"leidos":    true,
	"saic":      true,
	"mantech":   true,

	// US Logistics & Shipping
	"fedex":       true,
	"ups":         true,
	"usps":        true,
	"xpo":         true,
	"chmrobinson": true,
	"jbhunt":      true,

	// US Defense & Aerospace
	"lockheed":        true,
	"boeing":          true,
	"raytheon":        true,
	"northrop":        true,
	"generaldynamics": true,
	"l3harris":        true,
	"textron":         true,

	// US Energy
	"exxonmobil":     true,
	"exxon":          true,
	"chevron":        true,
	"conocophillips": true,
	"halliburton":    true,
	"slb":            true,
	"schlumberger":   true,
	"pioneer":        true,
	"devon":          true,
	"marathon":       true,
	"valero":         true,

	// US Insurance
	"geico":       true,
	"statefarm":   true,
	"progressive": true,
	"allstate":    true,
	"metlife":     true,
	"newyorklife": true,
	"tiaa":        true,
	"unum":        true,
	"aflac":       true,
	"cigna":       true,
	"humana":      true,
	"aetna":       true,

	// US Real Estate & Private Equity
	"zillow":     true,
	"redfin":     true,
	"opendoor":   true,
	"wework":     true,
	"cbre":       true,
	"jll":        true,
	"kkr":        true,
	"carlyle":    true,
	"blackstone": true,
	"apollo":     true,
	"tpg":        true,
	"warburg":    true,
}
