package account

// reservedVariants contains singular/plural completions derived from reservedNames.
// For every plural in reservedNames the singular is listed here, and for every
// singular in reservedNames the plural is listed here (where a natural form exists).
// All entries are blocked with the same error as reservedNames.
var reservedVariants = map[string]bool{
	// Singulars for plurals in reservedNames
	"agent":          true,
	"blueprint":      true,
	"setting":        true,
	"member":         true,
	"org":            true,
	"deployment":     true,
	"integration":    true,
	"invoice":        true,
	"job":            true,
	"log":            true,
	"metric":         true,
	"model":          true,
	"pipeline":       true,
	"plan":           true,
	"plugin":         true,
	"run":            true,
	"task":           true,
	"template":       true,
	"trace":          true,
	"workflow":       true,
	"cookie":         true,
	"term":           true,
	"career":         true,
	"partner":        true,
	"asset":          true,
	"file":           true,
	"upload":         true,
	"environment":    true,
	"error":          true,
	"event":          true,
	"message":        true,
	"notification":   true,
	"builder":        true,
	"case-study":     true,
	"customer":       true,
	"customer-story": true,
	"feature":        true,
	"image":          true,
	"investor":       true,
	"listing":        true,
	"nonprofit":      true,
	"page":           true,
	"payment":        true,
	"post":           true,
	"release":        true,
	"resource":       true,
	"service":        true,
	"session":        true,
	"shareholder":    true,
	"showcase":       true,
	"solution":       true,
	"sponsor":        true,
	"story":          true,
	"subscription":   true,
	"talk":           true,
	"translation":    true,
	"update":         true,

	// Plurals for singulars in reservedNames
	"enterprises":  true,
	"sites":        true,
	"admins":       true,
	"dashboards":   true,
	"apis":         true,
	"schemas":      true,
	"statuses":     true,
	"catalogs":     true,
	"checkouts":    true,
	"marketplaces": true,
	"blogs":        true,
	"changelogs":   true,
	"contacts":     true,
	"consoles":     true,
	"platforms":    true,
	"playgrounds":  true,
	"sandboxes":    true,
	"demos":        true,
	"previews":     true,
	"referrals":    true,
	"trials":       true,
	"edits":        true,
	"exports":      true,
	"imports":      true,
	"searches":     true,
	"transfers":    true,
	"operators":    true,
	"registries":   true,
	"systems":      true,
	"activities":   true,
	"audits":       true,
	"chats":        true,
	"feeds":        true,
	"hires":        true,
	"inboxes":      true,
}
