/**
 * One-shot: transcribes the palette data from @astropods/theme into a Go
 * source file. Run when color definitions change (rare).
 *
 *   bun run scripts/gen-theme.ts
 */

import { writeFileSync } from "fs";
import { resolve } from "path";
import { palettes, paletteNames } from "../src/theme";

const OUT = resolve(
  import.meta.dir,
  "../../../apps/astro-server/internal/identitygen/theme_data.go",
);

// Shades used by the identity generator (palette's "25" shade is intentionally excluded).
const SHADE_KEYS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;

const lines: string[] = [];
lines.push("// Code generated by packages/astro-identity-gen/scripts/gen-theme.ts; DO NOT EDIT.");
lines.push("");
lines.push("package identitygen");
lines.push("");
lines.push("// paletteNames enumerates palettes in insertion order — this ordering is");
lines.push("// load-bearing: generateIdentity's pick() indexes into it via rng.");
lines.push("var paletteNames = []string{");
for (const name of paletteNames) {
  lines.push(`\t"${name}",`);
}
lines.push("}");
lines.push("");
lines.push("// shadeKeys are the tailwind-style shade numbers used for identity colors,");
lines.push("// ordered light → dark. The \"25\" shade is deliberately omitted.");
lines.push("var shadeKeys = []int{50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950}");
lines.push("");
lines.push("// palettes maps palette name → shade → OKLCH color string.");
lines.push("var palettes = map[string]map[int]string{");
for (const name of paletteNames) {
  const scale = palettes[name];
  lines.push(`\t"${name}": {`);
  for (const shade of SHADE_KEYS) {
    const color = (scale as Record<number, string>)[shade];
    if (color === undefined) {
      throw new Error(`missing shade ${shade} for palette ${name}`);
    }
    lines.push(`\t\t${shade}: ${JSON.stringify(color)},`);
  }
  lines.push("\t},");
}
lines.push("}");
lines.push("");

writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${paletteNames.length} palettes × ${SHADE_KEYS.length} shades to ${OUT}`);
