/**
 * Semantic design tokens — single source of truth.
 *
 * Values are CSS custom-property references (var(--color-*)) that resolve
 * against the palette generated by colors.ts.  build-css.ts converts these
 * maps into :root / .dark blocks in dist/semantic.css.
 *
 * Only standard shadcn tokens are kept here:
 *   background, foreground, primary, primary-foreground, secondary,
 *   secondary-foreground, muted, muted-foreground, accent,
 *   accent-foreground, destructive, border, input, ring
 */

export const lightTheme = {
  background: "var(--color-stone-50)",
  foreground: "var(--color-teal-900)",
  popover: "var(--color-stone-25)",
  "popover-foreground": "var(--color-teal-900)",
  primary: "var(--color-teal-800)",
  "primary-foreground": "#fff",
  secondary: "var(--color-stone-200)",
  "secondary-foreground": "var(--color-stone-800)",
  muted: "var(--color-stone-200)",
  "muted-foreground": "var(--color-stone-700)",
  surface: "oklch(92.89% 0.0197 87.537)",
  ink: "oklch(32.72% 0.0524 193.0)",
  "ink-muted": "oklch(46.51% 0.0244 192.7)",
  "ink-faint": "oklch(57.71% 0.0225 188.9)",
  accent: "var(--color-stone-200)",
  "accent-foreground": "var(--color-stone-800)",
  destructive: "var(--color-red-700)",
  border: "var(--color-stone-300)",
  input: "var(--color-stone-300)",
  "input-background": "var(--color-stone-25)",
  "input-focus-ring": "color-mix(in oklch, var(--color-teal-600) 20%, transparent)",
  ring: "var(--color-teal-500)",
} as const;

export const darkTheme = {
  background: "var(--color-teal-950)",
  foreground: "var(--color-stone-100)",
  popover: "var(--color-stone-950)",
  "popover-foreground": "var(--color-stone-100)",
  primary: "var(--color-teal-400)",
  "primary-foreground": "var(--color-teal-950)",
  secondary: "var(--color-teal-800)",
  "secondary-foreground": "var(--color-stone-100)",
  muted: "var(--color-teal-800)",
  "muted-foreground": "var(--color-stone-600)",
  surface: "oklch(13% 0.0105 198.266)",
  ink: "var(--color-stone-100)",
  "ink-muted": "oklch(65% 0.0225 191.0)",
  "ink-faint": "oklch(55% 0.0200 189.0)",
  accent: "var(--color-teal-800)",
  "accent-foreground": "var(--color-stone-100)",
  destructive: "var(--color-red-800)",
  border: "color-mix(in oklch, var(--color-teal-300) 15%, transparent)",
  input: "color-mix(in oklch, var(--color-teal-300) 20%, transparent)",
  "input-background": "color-mix(in oklch, var(--color-stone-100) 5%, transparent)",
  "input-focus-ring": "color-mix(in oklch, var(--color-teal-400) 15%, transparent)",
  ring: "var(--color-teal-500)",
} as const;
