/**
 * Semantic design tokens — single source of truth.
 *
 * Values are CSS custom-property references (var(--color-*)) that resolve
 * against the palette generated by colors.ts.  build-css.ts converts these
 * maps into :root / .dark blocks in dist/semantic.css.
 *
 * The keys of `lightTheme` define the `SemanticToken` union; `darkTheme` is
 * typed as `Record<SemanticToken, string>` so any drift between the two
 * themes is a compile error (caught by `astro-theme:typecheck`).
 *
 * Elevation ladder (background tokens, lightest → most-lifted):
 *   background  - page chrome (rarely used directly)
 *   surface     - page body / panels (set on <html>/<body>)
 *   card        - lifted tiles (MetricCard, list cards, etc.)
 *   popover     - menus, dropdowns
 */

export const lightTheme = {
  background: "var(--color-stone-50)",
  foreground: "var(--color-stone-950)",
  popover: "var(--color-stone-25)",
  "popover-foreground": "var(--foreground)",
  primary: "var(--color-teal-800)",
  "primary-foreground": "#fff",
  secondary: "var(--color-stone-200)",
  "secondary-foreground": "var(--color-stone-800)",
  muted: "var(--color-stone-200)",
  "muted-foreground": "var(--color-stone-700)",
  surface: "var(--color-stone-100)",
  card: "#fff",
  "card-foreground": "var(--foreground)",
  "faint-foreground": "var(--color-stone-500)",
  "border-strong": "var(--color-stone-400)",
  "code-text": "oklch(82.90% 0.0224 182.6)",
  accent: "var(--color-stone-200)",
  "accent-foreground": "var(--color-stone-800)",
  destructive: "var(--color-red-700)",
  border: "var(--color-stone-300)",
  input: "var(--color-stone-300)",
  "input-background": "#fff",
  "input-focus-ring": "color-mix(in oklch, var(--color-teal-600) 20%, transparent)",
  ring: "var(--color-teal-500)",
} as const;

export type SemanticToken = keyof typeof lightTheme;

export const darkTheme: Record<SemanticToken, string> = {
  background: "var(--color-teal-950)",
  foreground: "var(--color-stone-100)",
  popover: "var(--color-stone-950)",
  "popover-foreground": "var(--color-stone-100)",
  primary: "var(--color-teal-400)",
  "primary-foreground": "var(--color-teal-950)",
  secondary: "var(--color-teal-800)",
  "secondary-foreground": "var(--color-stone-100)",
  muted: "oklch(17% 0.022 198.266)",
  "muted-foreground": "var(--color-teal-100)",
  surface: "oklch(13% 0.0105 198.266)",
  // One step lighter than `surface` so cards lift visibly above the page
  // body (which is `bg-surface`).
  card: "oklch(16% 0.011 198.266)",
  "card-foreground": "var(--foreground)",
  "faint-foreground": "var(--color-teal-300)",
  "border-strong": "color-mix(in oklch, var(--color-teal-300) 25%, transparent)",
  "code-text": "var(--color-teal-300)",
  accent: "var(--color-teal-800)",
  "accent-foreground": "var(--color-stone-100)",
  destructive: "var(--color-red-800)",
  border: "color-mix(in oklch, var(--color-teal-300) 15%, transparent)",
  input: "color-mix(in oklch, var(--color-teal-300) 20%, transparent)",
  "input-background": "color-mix(in oklch, var(--color-stone-100) 5%, transparent)",
  "input-focus-ring": "color-mix(in oklch, var(--color-teal-400) 15%, transparent)",
  ring: "var(--color-teal-500)",
};
