package deploymentstore

import (
	"database/sql"
	"fmt"
	"time"
)

// Store manages deployment record persistence in PostgreSQL.
type Store struct {
	db *sql.DB
}

// NewStore creates a new deployment store with the given database connection.
func NewStore(db *sql.DB) *Store {
	return &Store{db: db}
}

// Deployment represents a single deployment record.
type Deployment struct {
	ID                 string     `json:"id"`
	AccountID          string     `json:"account_id"`
	AgentName          string     `json:"agent_name"`
	BuildID            string     `json:"build_id"`
	Namespace          string     `json:"namespace"`
	DisplayName        string     `json:"display_name,omitempty"`
	DeploymentSpecJSON string     `json:"deployment_spec_json"`
	Status             string     `json:"status"`
	DeployedAt         time.Time  `json:"deployed_at"`
	UndeployedAt       *time.Time `json:"undeployed_at,omitempty"`
}

// SaveDeploymentParams holds the parameters for saving a deployment with normalized spec data.
type SaveDeploymentParams struct {
	ID               string
	AccountID        string
	AgentName        string
	DisplayName      string
	BuildID          string
	Namespace        string
	SpecJSON         string
	EncryptedDataKey []byte
	KMSKeyARN        string
}

// SaveDeployment marks the existing active deployment for the same agent+display_name
// as undeployed and inserts a new active deployment row, all within a transaction.
// The id and namespace are pre-generated by the caller (namespace is derived from the UUID).
func (s *Store) SaveDeployment(id, accountID, agentName, displayName, buildID, namespace, specJSON string) (*Deployment, error) {
	return s.SaveDeploymentFull(SaveDeploymentParams{
		ID: id, AccountID: accountID, AgentName: agentName,
		DisplayName: displayName, BuildID: buildID,
		Namespace: namespace, SpecJSON: specJSON,
	}, nil)
}

// SaveDeploymentFull saves a deployment with optional normalized spec data.
// If txFn is non-nil, it is called within the same transaction after the deployment
// row is inserted, allowing the caller to save normalized spec data atomically.
func (s *Store) SaveDeploymentFull(p SaveDeploymentParams, txFn func(tx *sql.Tx, deploymentID string) error) (*Deployment, error) {
	tx, err := s.db.Begin()
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck

	// Mark existing active deployment with same display_name as undeployed (redeploy case).
	if p.DisplayName != "" {
		_, err = tx.Exec(`
			UPDATE deployments
			SET status = 'undeployed', undeployed_at = NOW()
			WHERE account_id = $1 AND display_name = $2 AND status = 'active'
		`, p.AccountID, p.DisplayName)
	} else {
		_, err = tx.Exec(`
			UPDATE deployments
			SET status = 'undeployed', undeployed_at = NOW()
			WHERE account_id = $1 AND agent_name = $2 AND status = 'active'
			AND (SELECT COUNT(*) FROM deployments WHERE account_id = $1 AND agent_name = $2 AND status = 'active') = 1
		`, p.AccountID, p.AgentName)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to mark previous deployment: %w", err)
	}

	// Insert new active deployment with pre-generated ID
	var d Deployment
	err = tx.QueryRow(`
		INSERT INTO deployments (id, account_id, agent_name, build_id, namespace, display_name, deployment_spec_json, encrypted_data_key, kms_key_arn, status, deployed_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'active', NOW())
		RETURNING id, account_id, agent_name, build_id, namespace, display_name, deployment_spec_json, status, deployed_at
	`, p.ID, p.AccountID, p.AgentName, p.BuildID, p.Namespace, p.DisplayName, p.SpecJSON, p.EncryptedDataKey, nilIfEmpty(p.KMSKeyARN)).Scan(
		&d.ID, &d.AccountID, &d.AgentName, &d.BuildID, &d.Namespace,
		&d.DisplayName, &d.DeploymentSpecJSON, &d.Status, &d.DeployedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to insert deployment: %w", err)
	}

	// Run caller's transaction function (normalized spec save)
	if txFn != nil {
		if err := txFn(tx, d.ID); err != nil {
			return nil, fmt.Errorf("failed to save normalized spec: %w", err)
		}
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return &d, nil
}

func nilIfEmpty(s string) interface{} {
	if s == "" {
		return nil
	}
	return s
}

// GetDeploymentByID returns a deployment by its ID, or nil if not found.
func (s *Store) GetDeploymentByID(id string) (*Deployment, error) {
	var d Deployment
	err := s.db.QueryRow(`
		SELECT id, account_id, agent_name, build_id, namespace, display_name, deployment_spec_json, status, deployed_at, undeployed_at
		FROM deployments
		WHERE id = $1
	`, id).Scan(
		&d.ID, &d.AccountID, &d.AgentName, &d.BuildID, &d.Namespace,
		&d.DisplayName, &d.DeploymentSpecJSON, &d.Status, &d.DeployedAt, &d.UndeployedAt,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("failed to get deployment by ID: %w", err)
	}
	return &d, nil
}

// GetActiveDeployment returns the currently active deployment for an agent, or nil if none.
// If the agent has multiple active deployments, returns the most recently deployed.
func (s *Store) GetActiveDeployment(accountID, agentName string) (*Deployment, error) {
	var d Deployment
	err := s.db.QueryRow(`
		SELECT id, account_id, agent_name, build_id, namespace, display_name, deployment_spec_json, status, deployed_at, undeployed_at
		FROM deployments
		WHERE account_id = $1 AND agent_name = $2 AND status = 'active'
		ORDER BY deployed_at DESC
		LIMIT 1
	`, accountID, agentName).Scan(
		&d.ID, &d.AccountID, &d.AgentName, &d.BuildID, &d.Namespace,
		&d.DisplayName, &d.DeploymentSpecJSON, &d.Status, &d.DeployedAt, &d.UndeployedAt,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("failed to get active deployment: %w", err)
	}
	return &d, nil
}

// GetActiveDeployments returns all active deployments for an agent.
func (s *Store) GetActiveDeployments(accountID, agentName string) ([]*Deployment, error) {
	rows, err := s.db.Query(`
		SELECT id, account_id, agent_name, build_id, namespace, display_name, deployment_spec_json, status, deployed_at, undeployed_at
		FROM deployments
		WHERE account_id = $1 AND agent_name = $2 AND status = 'active'
		ORDER BY deployed_at DESC
	`, accountID, agentName)
	if err != nil {
		return nil, fmt.Errorf("failed to query active deployments: %w", err)
	}
	defer rows.Close() //nolint:errcheck

	var deployments []*Deployment
	for rows.Next() {
		var d Deployment
		if err := rows.Scan(
			&d.ID, &d.AccountID, &d.AgentName, &d.BuildID, &d.Namespace,
			&d.DisplayName, &d.DeploymentSpecJSON, &d.Status, &d.DeployedAt, &d.UndeployedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan deployment row: %w", err)
		}
		deployments = append(deployments, &d)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating deployment rows: %w", err)
	}
	return deployments, nil
}

// GetActiveDeploymentByDisplayName returns the active deployment with the given display name, or nil.
func (s *Store) GetActiveDeploymentByDisplayName(accountID, displayName string) (*Deployment, error) {
	var d Deployment
	err := s.db.QueryRow(`
		SELECT id, account_id, agent_name, build_id, namespace, display_name, deployment_spec_json, status, deployed_at, undeployed_at
		FROM deployments
		WHERE account_id = $1 AND display_name = $2 AND status = 'active'
	`, accountID, displayName).Scan(
		&d.ID, &d.AccountID, &d.AgentName, &d.BuildID, &d.Namespace,
		&d.DisplayName, &d.DeploymentSpecJSON, &d.Status, &d.DeployedAt, &d.UndeployedAt,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("failed to get active deployment by display name: %w", err)
	}
	return &d, nil
}

// GetActiveDeploymentsByAccount returns all active deployments for an account.
func (s *Store) GetActiveDeploymentsByAccount(accountID string) ([]*Deployment, error) {
	rows, err := s.db.Query(`
		SELECT id, account_id, agent_name, build_id, namespace, display_name, deployment_spec_json, status, deployed_at, undeployed_at
		FROM deployments
		WHERE account_id = $1 AND status = 'active'
		ORDER BY deployed_at DESC
	`, accountID)
	if err != nil {
		return nil, fmt.Errorf("failed to query active deployments by account: %w", err)
	}
	defer rows.Close() //nolint:errcheck

	var deployments []*Deployment
	for rows.Next() {
		var d Deployment
		if err := rows.Scan(
			&d.ID, &d.AccountID, &d.AgentName, &d.BuildID, &d.Namespace,
			&d.DisplayName, &d.DeploymentSpecJSON, &d.Status, &d.DeployedAt, &d.UndeployedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan deployment row: %w", err)
		}
		deployments = append(deployments, &d)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating deployment rows: %w", err)
	}
	return deployments, nil
}

// GetDeploymentHistory returns all deployment records for an agent, ordered by deployed_at DESC.
func (s *Store) GetDeploymentHistory(accountID, agentName string) ([]*Deployment, error) {
	rows, err := s.db.Query(`
		SELECT id, account_id, agent_name, build_id, namespace, display_name, deployment_spec_json, status, deployed_at, undeployed_at
		FROM deployments
		WHERE account_id = $1 AND agent_name = $2
		ORDER BY deployed_at DESC
	`, accountID, agentName)
	if err != nil {
		return nil, fmt.Errorf("failed to query deployment history: %w", err)
	}
	defer rows.Close() //nolint:errcheck

	var deployments []*Deployment
	for rows.Next() {
		var d Deployment
		if err := rows.Scan(
			&d.ID, &d.AccountID, &d.AgentName, &d.BuildID, &d.Namespace,
			&d.DisplayName, &d.DeploymentSpecJSON, &d.Status, &d.DeployedAt, &d.UndeployedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan deployment row: %w", err)
		}
		deployments = append(deployments, &d)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating deployment rows: %w", err)
	}
	return deployments, nil
}

// DeploymentWithAccount extends Deployment with the owning account name.
type DeploymentWithAccount struct {
	Deployment
	AccountName string `json:"account_name"`
}

// ListAllActive returns all active deployments across all accounts, joined with account names.
func (s *Store) ListAllActive() ([]*DeploymentWithAccount, error) {
	rows, err := s.db.Query(`
		SELECT d.id, d.account_id, d.agent_name, d.build_id, d.namespace, d.display_name,
		       d.deployment_spec_json, d.status, d.deployed_at, d.undeployed_at,
		       a.name AS account_name
		FROM deployments d
		JOIN accounts a ON d.account_id = a.id
		WHERE d.status = 'active'
		ORDER BY d.deployed_at DESC
	`)
	if err != nil {
		return nil, fmt.Errorf("failed to query all active deployments: %w", err)
	}
	defer rows.Close() //nolint:errcheck

	var deployments []*DeploymentWithAccount
	for rows.Next() {
		var d DeploymentWithAccount
		if err := rows.Scan(
			&d.ID, &d.AccountID, &d.AgentName, &d.BuildID, &d.Namespace, &d.DisplayName,
			&d.DeploymentSpecJSON, &d.Status, &d.DeployedAt, &d.UndeployedAt,
			&d.AccountName,
		); err != nil {
			return nil, fmt.Errorf("failed to scan deployment row: %w", err)
		}
		deployments = append(deployments, &d)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating deployment rows: %w", err)
	}
	return deployments, nil
}

// MarkUndeployedByID sets a specific deployment to 'undeployed'.
func (s *Store) MarkUndeployedByID(deploymentID string) error {
	_, err := s.db.Exec(`
		UPDATE deployments
		SET status = 'undeployed', undeployed_at = NOW()
		WHERE id = $1 AND status = 'active'
	`, deploymentID)
	if err != nil {
		return fmt.Errorf("failed to mark deployment as undeployed: %w", err)
	}
	return nil
}

// MarkUndeployed sets the active deployment for an agent to 'undeployed'.
// Deprecated: Use MarkUndeployedByID for multi-deployment support.
func (s *Store) MarkUndeployed(accountID, agentName string) error {
	_, err := s.db.Exec(`
		UPDATE deployments
		SET status = 'undeployed', undeployed_at = NOW()
		WHERE account_id = $1 AND agent_name = $2 AND status = 'active'
	`, accountID, agentName)
	if err != nil {
		return fmt.Errorf("failed to mark deployment as undeployed: %w", err)
	}
	return nil
}
