name: Database Rollout

on:
  push:
    branches:
      - main
    paths:
      - "apps/astro-server/migrations/*.sql"

env:
  BYTEBASE_URL: https://bytebase.astroids.ai/
  BYTEBASE_SERVICE_ACCOUNT: github-bot@service.bytebase.com
  BYTEBASE_SERVICE_ACCOUNT_SECRET: ${{ secrets.BYTEBASE_SERVICE_ACCOUNT_SECRET }}
  BYTEBASE_PROJECT: "projects/astro"

permissions:
  contents: read

jobs:
  create-rollout:
    runs-on: ubuntu-latest
    container:
      image: docker://bytebase/bytebase-action:latest
    outputs:
      plan: ${{ steps.rollout.outputs.plan }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create rollout plan
        id: rollout
        env:
          BYTEBASE_TARGETS: "instances/preview/databases/astro,instances/prod-postgresql/databases/astro"
          FILE_PATTERN: "apps/astro-server/migrations/*.sql"
          BYTEBASE_OUTPUT: ${{ runner.temp }}/bytebase-metadata.json
        run: |
          bytebase-action rollout --url=${{ env.BYTEBASE_URL }} --project=${{ env.BYTEBASE_PROJECT }} --file-pattern=${{ env.FILE_PATTERN }} --targets=${{ env.BYTEBASE_TARGETS }} --output=${{ env.BYTEBASE_OUTPUT }}
          PLAN=$(jq -r .plan ${{ env.BYTEBASE_OUTPUT }})
          echo "plan=$PLAN" >> $GITHUB_OUTPUT

  deploy-to-preview:
    needs: create-rollout
    runs-on: ubuntu-latest
    environment: preview
    container:
      image: docker://bytebase/bytebase-action:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to preview
        run: |
          bytebase-action rollout --url=${{ env.BYTEBASE_URL }} --project=${{ env.BYTEBASE_PROJECT }} --target-stage=environments/preview --plan=${{ needs.create-rollout.outputs.plan }}

  deploy-to-prod:
    needs: [create-rollout, deploy-to-preview]
    runs-on: ubuntu-latest
    environment: prod
    container:
      image: docker://bytebase/bytebase-action:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to prod
        run: |
          bytebase-action rollout --url=${{ env.BYTEBASE_URL }} --project=${{ env.BYTEBASE_PROJECT }} --target-stage=environments/prod --plan=${{ needs.create-rollout.outputs.plan }}
