name: Schema Migration

on:
  push:
    branches: [main]
    paths:
      - "apps/astro-server/schema.sql"

permissions:
  contents: read

env:
  BYTEBASE_URL: https://bytebase.astroids.ai/
  BYTEBASE_SERVICE_ACCOUNT: github-bot@service.bytebase.com
  BYTEBASE_SERVICE_ACCOUNT_SECRET: ${{ secrets.BYTEBASE_SERVICE_ACCOUNT_SECRET }}
  BYTEBASE_PROJECT: "projects/astro"
  FILE_PATTERN: "apps/astro-server/schema.sql"

jobs:
  rollout:
    runs-on: ubuntu-latest
    container:
      image: bytebase/bytebase-action:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create and execute rollout
        env:
          BYTEBASE_TARGETS: "instances/preview/databases/astro,instances/prod-postgresql/databases/astro"
        run: |
          bytebase-action rollout \
            --url=${{ env.BYTEBASE_URL }} \
            --project=${{ env.BYTEBASE_PROJECT }} \
            --file-pattern=${{ env.FILE_PATTERN }} \
            --targets=${{ env.BYTEBASE_TARGETS }} \
            --declarative
