name: Schema Migration

on:
  push:
    branches: [main]
    paths:
      - "apps/astro-server/schema.sql"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  BYTEBASE_URL: https://bytebase.astroids.ai/
  BYTEBASE_SERVICE_ACCOUNT: github-bot@service.bytebase.com
  BYTEBASE_SERVICE_ACCOUNT_SECRET: ${{ secrets.BYTEBASE_SERVICE_ACCOUNT_SECRET }}
  BYTEBASE_PROJECT: "projects/astro"
  FILE_PATTERN: "apps/astro-server/schema.sql"

jobs:
  create-rollout:
    runs-on: ubuntu-latest
    container:
      image: bytebase/bytebase-action:latest
    outputs:
      plan: ${{ steps.set-output.outputs.plan }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create rollout plan
        env:
          BYTEBASE_TARGETS: "instances/prod-postgresql/databases/astro"
          BYTEBASE_OUTPUT: ${{ runner.temp }}/bytebase-metadata.json
        run: |
          bytebase-action rollout \
            --url=${{ env.BYTEBASE_URL }} \
            --project=${{ env.BYTEBASE_PROJECT }} \
            --file-pattern=${{ env.FILE_PATTERN }} \
            --targets=${{ env.BYTEBASE_TARGETS }} \
            --declarative \
            --output=${{ env.BYTEBASE_OUTPUT }}
      - name: Set output
        id: set-output
        run: |
          PLAN=$(jq -r .plan ${{ runner.temp }}/bytebase-metadata.json)
          echo "plan=$PLAN" >> $GITHUB_OUTPUT

  deploy-to-prod:
    needs: create-rollout
    runs-on: ubuntu-latest
    environment: prod
    container:
      image: bytebase/bytebase-action:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Roll out to prod
        run: |
          bytebase-action rollout \
            --url=${{ env.BYTEBASE_URL }} \
            --project=${{ env.BYTEBASE_PROJECT }} \
            --target-stage=environments/prod \
            --plan=${{ needs.create-rollout.outputs.plan }}
