name: SQL Review

on:
  pull_request:
    paths:
      - "apps/astro-server/schema.sql"

jobs:
  squawk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install squawk
        run: npm install -g squawk-cli
      - name: Lint schema
        run: squawk apps/astro-server/schema.sql
